'''Set up your config here and than use it on main.py'''
base_url: 'https://qjma.atu.ac.ir/'
headless: true
journal_name: 'Journal Name'
issue_xpath: '//*[@class="article_new"]'
issue_link_xpath: '//a[contains(@href, "issue_")]'
article_link_xpath: '//a[contains(@href, "article_")]'
title_fa_xpath: '//*[@class="page-header"]'
title_en_xpath: '//*[@class="page-content"]/div[2]/p[2]'
authors_fa_xpath: '//*[@id="info_content"]//ul[@class="list-inline list-inline-seprator margin-bottom-6 rtl"]/li | //p[@class="margin-bottom-3 rtl"]'
authors_en_xpath: '//*[@id="info_content"]//ul[@class="list-inline list-inline-seprator margin-bottom-6"]/li |//p[@class="margin-bottom-3" and @style="direction:ltr"]'
keywords_fa_xpath: '//*[@class="block list-inline list-inline-seprator margin-bottom-6 rtl"]'
keywords_en_xpath: '//*[@class="block list-inline list-inline-seprator margin-bottom-6" and @style="direction:ltr"]/li'
abstract_fa_xpath: '//*[@class="justify_txt rtl"]'
abstract_en_xpath: '//*[@class="justify_txt" and @style="direction:ltr"]'
year_xpath: '//*[@style="margin-top:0px;"]'
references_toggle_xpath: '//*[@id="info_content"]//a[@data-toggle="collapse"]'
references_rtl_xpath: '//*[@class="panel-body"]/ol/li[@class="rtl justify"] | //div[@class="padding-3 margin-top-3 rtl justify"]'
references_ltr_xpath: '//*[@class="panel-body"]/ol/li[@class="ltr justify"] | //div[@class="padding-3 margin-top-3 rtl justify"]'
